### ISSUE TITLE
pretty nice - this is dead ?

### ISSUE THREAD

**Issue by joeblew99** [splace/golang-raytracing-2d#2]
I was wondering about sub pixel anti-aliasing, but then i realised as i read the readme there is not code :)

**Comment by splace** [comment]
thanks for the interest, not dead honestly.

but i haven’t pushed any code because i've been wondering if i had done it the 'wrong' way.....

a. because this isn't the go way; i've used functions calling functions and stored state in closures.
b. if i had used struct's and interface's, then i could keep track of and later alter any parameter.
c. struct hierarchies could be marshalled using the std lib., and so be saved as a textual representation (Generative Modelling)

but since trying this on another project, i now think.....

a. does it matter
b. the hierarchy of functions is relatively cheap to recreate
c. interface types can not be marshalled by the std lib.

and as for anti-aliasing;  procedural generation allows you to sample anywhere, i just sample diagonally half way between pixels and average; (basic/fast AA) 

![line 2 44 aa](https://cloud.githubusercontent.com/assets/1234848/12699693/5a2d7d58-c7bc-11e5-8036-90496daf1c94.png)

**Comment by joeblew99** [comment]
I say throw it up. Live and let live...
I am thinking of using it in a little experiment with real time graphics.
Basically I want to stream high data video streams uncompressed and screw
with them. Running credits, image manipulation etc.
To keep the stream truely real time, I plan to assign chunks of frames to
different servers.

I used to work in CGI industry donkeys years ago and its a itch I want to
scratch just too see where it goes.

Cheers :)

Joe

**Comment by splace** [comment]
sounds like you could do what you want with the standard image package, i dont know of a package to pull/push frames from a video stream though, but image could overlay text/graphics/images to a frame.

you could use this project to make a large library of pre-drawn images, used for above, but you could also use SVG, or others, to do that.

this project seems only useful when you basically would never need exactly the same image twice, and then not counting simple image variation using tiling or layering.
